version: '3.8'
services:
  db:
    image: bitnami/postgresql
    container_name: booking_postgres
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Anahit123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
